import {
  Menu,
  Sun,
  Moon,
  Phone,
  Mail,
  MessageCircle,
  User,
  Settings,
  Calendar,
  Shield,
  LogOut,
  Laptop,
  ChevronDown,
  Star,
  MapPin,
  Clock,
  Users,
  Heart,
  Award,
  Globe,
  Image,
  Plane,
  Mountain,
  Waves,
  TreePine,
  Compass,
  Navigation,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  ExternalLink,
  Download,
  Upload,
  Share,
  Copy,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Home,
  Building,
  Car,
  Bus,
  Train,
  Ship,
  Bed,
  Utensils,
  Coffee,
  Wine,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Euro,
  PoundSterling,
  JapaneseYenIcon as Yen,
  Bitcoin,
  Wallet,
  Receipt,
  Calculator,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Zap,
  Battery,
  Wifi,
  WifiOff,
  Signal,
  Bluetooth,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Mic,
  MicOff,
  Video,
  VideoOff,
  FileText,
  File,
  Folder,
  FolderOpen,
  Archive,
  Bookmark,
  Tag,
  Flag,
  Bell,
  BellOff,
  MessageSquare,
  Send,
  Paperclip,
  Smile,
  ThumbsUp,
  ThumbsDown,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin,
  Github,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  menu: Menu,
  sun: Sun,
  moon: Moon,
  phone: Phone,
  mail: Mail,
  messageCircle: MessageCircle,
  user: User,
  settings: Settings,
  calendar: Calendar,
  shield: Shield,
  logOut: LogOut,
  laptop: Laptop,
  chevronDown: ChevronDown,
  star: Star,
  mapPin: MapPin,
  clock: Clock,
  users: Users,
  heart: Heart,
  award: Award,
  globe: Globe,
  image: Image,
  plane: Plane,
  mountain: Mountain,
  waves: Waves,
  treePine: TreePine,
  compass: Compass,
  navigation: Navigation,
  search: Search,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  grid: Grid,
  list: List,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash2: Trash2,
  save: Save,
  x: X,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,
  externalLink: ExternalLink,
  download: Download,
  upload: Upload,
  share: Share,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userX: UserX,
  home: Home,
  building: Building,
  car: Car,
  bus: Bus,
  train: Train,
  ship: Ship,
  bed: Bed,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  shoppingBag: ShoppingBag,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  euro: Euro,
  poundSterling: PoundSterling,
  yen: Yen,
  bitcoin: Bitcoin,
  wallet: Wallet,
  receipt: Receipt,
  calculator: Calculator,
  barChart: BarChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: Activity,
  zap: Zap,
  battery: Battery,
  wifi: Wifi,
  wifiOff: WifiOff,
  signal: Signal,
  bluetooth: Bluetooth,
  volume2: Volume2,
  volumeX: VolumeX,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,
  mic: Mic,
  micOff: MicOff,
  video: Video,
  videoOff: VideoOff,
  fileText: FileText,
  file: File,
  folder: Folder,
  folderOpen: FolderOpen,
  archive: Archive,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,
  bell: Bell,
  bellOff: BellOff,
  messageSquare: MessageSquare,
  send: Send,
  paperclip: Paperclip,
  smile: Smile,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  github: Github,
}
